export type CssColorVariableName = `--${string}`;

export type DcmPrimitiveGroup =
  | 'Brand'
  | 'Secondary Deep'
  | 'Ink'
  | 'Success'
  | 'Warn'
  | 'Danger'
  | 'Info';

export type DcmSemanticGroup =
  | 'Text'
  | 'Surface'
  | 'Border'
  | 'Status'
  | 'Badge'
  | 'Focus';

export type DcmThemeAdaptation =
  | 'Runtime dark adaptation'
  | 'Runtime dark adaptation through the surface source graph';

export type DcmPrimitiveToken = Readonly<{
  name: CssColorVariableName;
  kind: 'primitive';
  group: DcmPrimitiveGroup;
  sourceValue: string;
  lightResolvedValue: string;
  description: string;
  aliases: readonly CssColorVariableName[];
}>;

export type DcmSemanticToken = Readonly<{
  name: CssColorVariableName;
  kind: 'semantic';
  group: DcmSemanticGroup;
  sourceValue: string;
  lightResolvedValue: string;
  description: string;
  aliases: readonly CssColorVariableName[];
  themeAdaptation: DcmThemeAdaptation;
  sourceAnnotation?: string;
}>;

export type DcmColorToken = DcmPrimitiveToken | DcmSemanticToken;

export type ColorAlias = Readonly<{
  name: CssColorVariableName;
  target: CssColorVariableName;
  description: string;
  via?: readonly CssColorVariableName[];
}>;

export type KuraColorExtension = Readonly<{
  name: CssColorVariableName;
  group: string;
  value: string;
  description: string;
  swatch: boolean;
}>;

export type DcmSemanticTone =
  | 'neutral'
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'ai'
  | 'brand';

export type DcmSemanticToneRule = Readonly<{
  tone: DcmSemanticTone;
  meanings: readonly string[];
  foreground: CssColorVariableName;
  background?: CssColorVariableName;
  requirement: 'Text or icon cue required; never color-only';
  description: string;
}>;

export const DCM_PRIMITIVE_TOKENS = [
  {
    name: '--color-brand-25',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#eef7ff',
    lightResolvedValue: '#eef7ff',
    description: 'Lightest brand tint for selected and contextual backgrounds.',
    aliases: ['--brand-25'],
  },
  {
    name: '--color-brand-50',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#e9f3ff',
    lightResolvedValue: '#e9f3ff',
    description: 'Light brand tint for active and highlighted surfaces.',
    aliases: ['--brand-50'],
  },
  {
    name: '--color-brand-100',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#d4e8ff',
    lightResolvedValue: '#d4e8ff',
    description: 'Brand tint for subtle emphasis and supportive borders.',
    aliases: ['--brand-100'],
  },
  {
    name: '--color-brand-500',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#268cff',
    lightResolvedValue: '#268cff',
    description: 'Core Kura blue for primary action and active focus.',
    aliases: ['--brand-500'],
  },
  {
    name: '--color-brand-600',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#1e70cc',
    lightResolvedValue: '#1e70cc',
    description: 'Strong brand blue for pressed and high-emphasis action.',
    aliases: ['--brand-600'],
  },
  {
    name: '--color-brand-700',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#175499',
    lightResolvedValue: '#175499',
    description: 'Deep brand blue for accessible links and strong accents.',
    aliases: ['--brand-700', '--color-text-link-hover'],
  },
  {
    name: '--color-brand-800',
    kind: 'primitive',
    group: 'Brand',
    sourceValue: '#0f3866',
    lightResolvedValue: '#0f3866',
    description: 'Darkest canonical brand step for restrained emphasis.',
    aliases: ['--brand-800'],
  },
  {
    name: '--color-secondary-deep-500',
    kind: 'primitive',
    group: 'Secondary Deep',
    sourceValue: '#10069f',
    lightResolvedValue: '#10069f',
    description: 'Canonical deep secondary accent.',
    aliases: ['--secondary-deep-500'],
  },
  {
    name: '--color-ink-0',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#ffffff',
    lightResolvedValue: '#ffffff',
    description: 'White ink endpoint for inverse content and surfaces.',
    aliases: ['--ink-0'],
  },
  {
    name: '--color-ink-25',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#f8f9fc',
    lightResolvedValue: '#f8f9fc',
    description: 'Near-white neutral for subtle containers and badges.',
    aliases: ['--ink-25'],
  },
  {
    name: '--color-ink-50',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#f6f7fa',
    lightResolvedValue: '#f6f7fa',
    description: 'Soft neutral background step.',
    aliases: ['--ink-50'],
  },
  {
    name: '--color-ink-100',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#eef0f5',
    lightResolvedValue: '#eef0f5',
    description: 'Sunken neutral surface and neutral status background.',
    aliases: ['--ink-100'],
  },
  {
    name: '--color-ink-150',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#e3e6ee',
    lightResolvedValue: '#e3e6ee',
    description: 'Subtle neutral divider and badge border step.',
    aliases: ['--ink-150'],
  },
  {
    name: '--color-ink-200',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#d6dae5',
    lightResolvedValue: '#d6dae5',
    description: 'Strong neutral border step.',
    aliases: ['--ink-200'],
  },
  {
    name: '--color-ink-400',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#8d94a8',
    lightResolvedValue: '#8d94a8',
    description: 'Muted neutral used by the DCM text-muted migration alias.',
    aliases: ['--ink-400', '--text-muted', '--color-text-placeholder'],
  },
  {
    name: '--color-ink-500',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#6b7388',
    lightResolvedValue: '#6b7388',
    description: 'Tertiary neutral for metadata and supporting content.',
    aliases: ['--ink-500'],
  },
  {
    name: '--color-ink-600',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#475066',
    lightResolvedValue: '#475066',
    description: 'Secondary text and neutral foreground step.',
    aliases: ['--ink-600'],
  },
  {
    name: '--color-ink-700',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#2a3447',
    lightResolvedValue: '#2a3447',
    description: 'Strong neutral foreground for labels and badge content.',
    aliases: ['--ink-700'],
  },
  {
    name: '--color-ink-900',
    kind: 'primitive',
    group: 'Ink',
    sourceValue: '#0b1424',
    lightResolvedValue: '#0b1424',
    description: 'Dark neutral endpoint for highest-emphasis ink.',
    aliases: ['--ink-900'],
  },
  {
    name: '--color-success-25',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#edf9f3',
    lightResolvedValue: '#edf9f3',
    description: 'Lightest success tint.',
    aliases: ['--success-25'],
  },
  {
    name: '--color-success-50',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#e7f8ee',
    lightResolvedValue: '#e7f8ee',
    description: 'Success status background.',
    aliases: ['--success-50'],
  },
  {
    name: '--color-success-100',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#c7eed7',
    lightResolvedValue: '#c7eed7',
    description: 'Soft success border and emphasis tint.',
    aliases: ['--success-100'],
  },
  {
    name: '--color-success-200',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#9ee4b9',
    lightResolvedValue: '#9ee4b9',
    description: 'Medium success tint.',
    aliases: ['--success-200'],
  },
  {
    name: '--color-success-500',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#1aa163',
    lightResolvedValue: '#1aa163',
    description: 'Core success accent.',
    aliases: ['--success-500'],
  },
  {
    name: '--color-success-600',
    kind: 'primitive',
    group: 'Success',
    sourceValue: '#128a52',
    lightResolvedValue: '#128a52',
    description: 'Accessible success foreground.',
    aliases: ['--success-600'],
  },
  {
    name: '--color-warn-25',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#fff9ea',
    lightResolvedValue: '#fff9ea',
    description: 'Lightest warning tint.',
    aliases: ['--warn-25'],
  },
  {
    name: '--color-warn-50',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#fff8e6',
    lightResolvedValue: '#fff8e6',
    description: 'Warning status background.',
    aliases: ['--warn-50'],
  },
  {
    name: '--color-warn-100',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#fdecc4',
    lightResolvedValue: '#fdecc4',
    description: 'Soft warning border and emphasis tint.',
    aliases: ['--warn-100'],
  },
  {
    name: '--color-warn-200',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#fbdb91',
    lightResolvedValue: '#fbdb91',
    description: 'Medium warning tint.',
    aliases: ['--warn-200'],
  },
  {
    name: '--color-warn-500',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#d97706',
    lightResolvedValue: '#d97706',
    description: 'Core warning accent.',
    aliases: ['--warn-500'],
  },
  {
    name: '--color-warn-600',
    kind: 'primitive',
    group: 'Warn',
    sourceValue: '#8a5600',
    lightResolvedValue: '#8a5600',
    description: 'Accessible warning foreground.',
    aliases: ['--warn-600'],
  },
  {
    name: '--color-danger-25',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#fff1f1',
    lightResolvedValue: '#fff1f1',
    description: 'Lightest danger tint.',
    aliases: ['--danger-25'],
  },
  {
    name: '--color-danger-50',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#fdecec',
    lightResolvedValue: '#fdecec',
    description: 'Danger status background.',
    aliases: ['--danger-50'],
  },
  {
    name: '--color-danger-100',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#fbd1d1',
    lightResolvedValue: '#fbd1d1',
    description: 'Soft danger border and emphasis tint.',
    aliases: ['--danger-100'],
  },
  {
    name: '--color-danger-200',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#f7a8a8',
    lightResolvedValue: '#f7a8a8',
    description: 'Medium danger tint.',
    aliases: ['--danger-200'],
  },
  {
    name: '--color-danger-400',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#e75f5f',
    lightResolvedValue: '#e75f5f',
    description: 'Bright danger emphasis step.',
    aliases: ['--danger-400'],
  },
  {
    name: '--color-danger-500',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#d83a3a',
    lightResolvedValue: '#d83a3a',
    description: 'Core danger accent.',
    aliases: ['--danger-500'],
  },
  {
    name: '--color-danger-600',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#b22929',
    lightResolvedValue: '#b22929',
    description: 'Accessible danger foreground.',
    aliases: ['--danger-600'],
  },
  {
    name: '--color-danger-700',
    kind: 'primitive',
    group: 'Danger',
    sourceValue: '#891f1f',
    lightResolvedValue: '#891f1f',
    description: 'Deep danger endpoint for critical emphasis.',
    aliases: ['--danger-700'],
  },
  {
    name: '--color-info-100',
    kind: 'primitive',
    group: 'Info',
    sourceValue: '#c3eef7',
    lightResolvedValue: '#c3eef7',
    description: 'Soft informational tint.',
    aliases: ['--info-100'],
  },
  {
    name: '--color-info-500',
    kind: 'primitive',
    group: 'Info',
    sourceValue: '#0e7490',
    lightResolvedValue: '#0e7490',
    description: 'Core informational foreground.',
    aliases: ['--info-500'],
  },
  {
    name: '--color-info-600',
    kind: 'primitive',
    group: 'Info',
    sourceValue: '#0a5a72',
    lightResolvedValue: '#0a5a72',
    description: 'Strong informational accent.',
    aliases: ['--info-600'],
  },
] as const satisfies readonly DcmPrimitiveToken[];

const runtimeDarkAdaptation: DcmThemeAdaptation = 'Runtime dark adaptation';

export const DCM_SEMANTIC_TOKENS = [
  {
    name: '--color-text-primary',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#1a2335',
    lightResolvedValue: '#1a2335',
    description: 'Highest-emphasis body and heading text.',
    aliases: ['--text-primary'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-secondary',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#475066',
    lightResolvedValue: '#475066',
    description: 'Supporting text with reduced emphasis.',
    aliases: ['--text-secondary'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-tertiary',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#6b7388',
    lightResolvedValue: '#6b7388',
    description: 'Metadata, captions, and tertiary information.',
    aliases: ['--text-tertiary', '--color-text-muted'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-disabled',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#b3b9c9',
    lightResolvedValue: '#b3b9c9',
    description: 'Unavailable or disabled content.',
    aliases: [],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-inverse',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#ffffff',
    lightResolvedValue: '#ffffff',
    description: 'Text placed on strongly contrasting surfaces.',
    aliases: [],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-on-brand',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#ffffff',
    lightResolvedValue: '#ffffff',
    description: 'Text and icons placed on brand-filled controls.',
    aliases: ['--text-on-brand'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-brand',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#268cff',
    lightResolvedValue: '#268cff',
    description: 'Brand-colored text for selected and active context.',
    aliases: [],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-text-link',
    kind: 'semantic',
    group: 'Text',
    sourceValue: '#175499',
    lightResolvedValue: '#175499',
    description: 'Accessible inline and navigational link text.',
    aliases: [],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-surface',
    kind: 'semantic',
    group: 'Surface',
    sourceValue: '#ffffff',
    lightResolvedValue: '#ffffff',
    description: 'Primary raised content surface.',
    aliases: ['--surface', '--surface-raised'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-surface-2',
    kind: 'semantic',
    group: 'Surface',
    sourceValue: '#fafbfd',
    lightResolvedValue: '#fafbfd',
    description: 'Secondary content surface with subtle separation.',
    aliases: ['--surface-2'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-surface-sunken',
    kind: 'semantic',
    group: 'Surface',
    sourceValue: '#eef0f5',
    lightResolvedValue: '#eef0f5',
    description: 'Recessed surface for grouped and inset content.',
    aliases: ['--surface-sunken'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-surface-bg',
    kind: 'semantic',
    group: 'Surface',
    sourceValue: 'var(--surface-bg, #ffffff)',
    lightResolvedValue: '#ffffff',
    description: 'Page background resolved through the sanctioned source-input graph.',
    aliases: ['--surface-bg', '--bg'],
    themeAdaptation: 'Runtime dark adaptation through the surface source graph',
  },
  {
    name: '--color-border',
    kind: 'semantic',
    group: 'Border',
    sourceValue: '#e6e9f1',
    lightResolvedValue: '#e6e9f1',
    description: 'Default boundary and divider.',
    aliases: ['--border', '--border-color'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-border-strong',
    kind: 'semantic',
    group: 'Border',
    sourceValue: '#d6dae5',
    lightResolvedValue: '#d6dae5',
    description: 'Higher-emphasis boundary.',
    aliases: ['--border-strong'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-border-emphasis',
    kind: 'semantic',
    group: 'Border',
    sourceValue: '#b3b9c9',
    lightResolvedValue: '#b3b9c9',
    description: 'Strongest neutral boundary for emphasized separation.',
    aliases: ['--border-emphasis'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-border-focus',
    kind: 'semantic',
    group: 'Border',
    sourceValue: '#268cff',
    lightResolvedValue: '#268cff',
    description: 'Solid focus boundary and active-control outline.',
    aliases: ['--border-focus'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-success-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#128a52',
    lightResolvedValue: '#128a52',
    description: 'Foreground for completed, verified, in-range, or stable states.',
    aliases: ['--status-success-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-success-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#e7f8ee',
    lightResolvedValue: '#e7f8ee',
    description: 'Background for completed, verified, in-range, or stable states.',
    aliases: ['--status-success-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-warning-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#8a5600',
    lightResolvedValue: '#8a5600',
    description: 'Foreground for pending, review, out-of-reference, or recoverable states.',
    aliases: ['--status-warning-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-warning-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#fff8e6',
    lightResolvedValue: '#fff8e6',
    description: 'Background for pending, review, out-of-reference, or recoverable states.',
    aliases: ['--status-warning-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-low-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#c5651c',
    lightResolvedValue: '#c5651c',
    description: 'Lone DCM foreground role for low results; no low background role exists.',
    aliases: ['--status-low-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-danger-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#b22929',
    lightResolvedValue: '#b22929',
    description: 'Foreground for critical, destructive, blocked, privacy, safety, or payment failure.',
    aliases: ['--status-danger-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-danger-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#fdecec',
    lightResolvedValue: '#fdecec',
    description: 'Background for critical, destructive, blocked, privacy, safety, or payment failure.',
    aliases: ['--status-danger-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-neutral-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#475066',
    lightResolvedValue: '#475066',
    description: 'Foreground for normal, inactive, unknown, or no-reference states.',
    aliases: ['--status-neutral-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-neutral-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#eef0f5',
    lightResolvedValue: '#eef0f5',
    description: 'Background for normal, inactive, unknown, or no-reference states.',
    aliases: ['--status-neutral-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-info-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#0e7490',
    lightResolvedValue: '#0e7490',
    description: 'Foreground for informational states.',
    aliases: ['--status-info-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-info-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#e6f9fd',
    lightResolvedValue: '#e6f9fd',
    description: 'Background for informational states.',
    aliases: ['--status-info-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-ai-fg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#6a35c0',
    lightResolvedValue: '#6a35c0',
    description: 'Foreground reserved for AI-assisted or generated insight.',
    aliases: ['--status-ai-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-status-ai-bg',
    kind: 'semantic',
    group: 'Status',
    sourceValue: '#f1ecfb',
    lightResolvedValue: '#f1ecfb',
    description: 'Background reserved for AI-assisted or generated insight.',
    aliases: ['--status-ai-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-neutral-bg',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#f8f9fc',
    lightResolvedValue: '#f8f9fc',
    description: 'Neutral badge background.',
    aliases: ['--badge-neutral-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-neutral-fg',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#2a3447',
    lightResolvedValue: '#2a3447',
    description: 'Neutral badge foreground.',
    aliases: ['--badge-neutral-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-neutral-border',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#e3e6ee',
    lightResolvedValue: '#e3e6ee',
    description: 'Neutral badge boundary.',
    aliases: ['--badge-neutral-border'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-neutral-icon',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#6b7388',
    lightResolvedValue: '#6b7388',
    description: 'Neutral badge icon foreground.',
    aliases: ['--badge-neutral-icon'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-warning-bg',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#fff9ea',
    lightResolvedValue: '#fff9ea',
    description: 'Warning badge background.',
    aliases: ['--badge-warning-bg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-warning-fg',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#6a4200',
    lightResolvedValue: '#6a4200',
    description: 'Warning badge foreground.',
    aliases: ['--badge-warning-fg'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-badge-warning-icon',
    kind: 'semantic',
    group: 'Badge',
    sourceValue: '#d97706',
    lightResolvedValue: '#d97706',
    description: 'Warning badge icon foreground.',
    aliases: ['--badge-warning-icon'],
    themeAdaptation: runtimeDarkAdaptation,
  },
  {
    name: '--color-focus-ring',
    kind: 'semantic',
    group: 'Focus',
    sourceValue: 'rgba(38, 140, 255, 0.32)',
    lightResolvedValue: 'rgba(38, 140, 255, 0.32)',
    sourceAnnotation: '#268cff52',
    description: 'Translucent focus halo for keyboard-visible focus.',
    aliases: [],
    themeAdaptation: runtimeDarkAdaptation,
  },
] as const satisfies readonly DcmSemanticToken[];

export const DCM_COLOR_TOKENS = [
  ...DCM_PRIMITIVE_TOKENS,
  ...DCM_SEMANTIC_TOKENS,
] as const satisfies readonly DcmColorToken[];

export const DCM_COLOR_MIGRATION_ALIASES = [
  { name: '--ink-0', target: '--color-ink-0', description: 'DCM primitive migration alias.' },
  { name: '--ink-25', target: '--color-ink-25', description: 'DCM primitive migration alias.' },
  { name: '--ink-100', target: '--color-ink-100', description: 'DCM primitive migration alias.' },
  { name: '--ink-150', target: '--color-ink-150', description: 'DCM primitive migration alias.' },
  { name: '--ink-400', target: '--color-ink-400', description: 'DCM primitive migration alias.' },
  { name: '--ink-500', target: '--color-ink-500', description: 'DCM primitive migration alias.' },
  { name: '--ink-600', target: '--color-ink-600', description: 'DCM primitive migration alias.' },
  { name: '--ink-700', target: '--color-ink-700', description: 'DCM primitive migration alias.' },
  { name: '--ink-900', target: '--color-ink-900', description: 'DCM primitive migration alias.' },
  { name: '--brand-25', target: '--color-brand-25', description: 'DCM primitive migration alias.' },
  { name: '--brand-50', target: '--color-brand-50', description: 'DCM primitive migration alias.' },
  { name: '--brand-500', target: '--color-brand-500', description: 'DCM primitive migration alias.' },
  { name: '--brand-700', target: '--color-brand-700', description: 'DCM primitive migration alias.' },
  { name: '--surface', target: '--color-surface', description: 'DCM surface migration alias.' },
  { name: '--surface-2', target: '--color-surface-2', description: 'DCM surface migration alias.' },
  { name: '--surface-sunken', target: '--color-surface-sunken', description: 'DCM surface migration alias.' },
  {
    name: '--border',
    target: '--color-border',
    via: ['--border-color'],
    description: 'DCM border alias resolved through the existing shadcn bridge.',
  },
  { name: '--border-strong', target: '--color-border-strong', description: 'DCM border migration alias.' },
  { name: '--text-primary', target: '--color-text-primary', description: 'DCM text migration alias.' },
  { name: '--text-secondary', target: '--color-text-secondary', description: 'DCM text migration alias.' },
  { name: '--text-tertiary', target: '--color-text-tertiary', description: 'DCM text migration alias.' },
  {
    name: '--text-muted',
    target: '--color-ink-400',
    description: 'DCM muted text alias resolving to #8d94a8 in light mode.',
  },
  { name: '--text-on-brand', target: '--color-text-on-brand', description: 'DCM text migration alias.' },
  { name: '--badge-neutral-bg', target: '--color-badge-neutral-bg', description: 'DCM badge migration alias.' },
  { name: '--badge-neutral-fg', target: '--color-badge-neutral-fg', description: 'DCM badge migration alias.' },
  { name: '--badge-warning-bg', target: '--color-badge-warning-bg', description: 'DCM badge migration alias.' },
  { name: '--badge-warning-fg', target: '--color-badge-warning-fg', description: 'DCM badge migration alias.' },
  { name: '--status-neutral-bg', target: '--color-status-neutral-bg', description: 'DCM status migration alias.' },
  { name: '--status-neutral-fg', target: '--color-status-neutral-fg', description: 'DCM status migration alias.' },
  { name: '--status-success-bg', target: '--color-status-success-bg', description: 'DCM status migration alias.' },
  { name: '--status-success-fg', target: '--color-status-success-fg', description: 'DCM status migration alias.' },
  { name: '--status-warning-bg', target: '--color-status-warning-bg', description: 'DCM status migration alias.' },
  { name: '--status-warning-fg', target: '--color-status-warning-fg', description: 'DCM status migration alias.' },
  { name: '--status-danger-bg', target: '--color-status-danger-bg', description: 'DCM status migration alias.' },
  { name: '--status-danger-fg', target: '--color-status-danger-fg', description: 'DCM status migration alias.' },
  { name: '--status-info-bg', target: '--color-status-info-bg', description: 'DCM status migration alias.' },
  { name: '--status-info-fg', target: '--color-status-info-fg', description: 'DCM status migration alias.' },
] as const satisfies readonly ColorAlias[];

export const KURA_COLOR_COMPATIBILITY_ALIASES = [
  { name: '--brand-100', target: '--color-brand-100', description: 'Kura short-ramp compatibility alias.' },
  { name: '--brand-600', target: '--color-brand-600', description: 'Kura short-ramp compatibility alias.' },
  { name: '--brand-800', target: '--color-brand-800', description: 'Kura short-ramp compatibility alias.' },
  { name: '--secondary-deep-500', target: '--color-secondary-deep-500', description: 'Kura short-ramp compatibility alias.' },
  { name: '--ink-50', target: '--color-ink-50', description: 'Kura short-ramp compatibility alias.' },
  { name: '--ink-200', target: '--color-ink-200', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-25', target: '--color-success-25', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-50', target: '--color-success-50', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-100', target: '--color-success-100', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-200', target: '--color-success-200', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-500', target: '--color-success-500', description: 'Kura short-ramp compatibility alias.' },
  { name: '--success-600', target: '--color-success-600', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-25', target: '--color-warn-25', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-50', target: '--color-warn-50', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-100', target: '--color-warn-100', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-200', target: '--color-warn-200', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-500', target: '--color-warn-500', description: 'Kura short-ramp compatibility alias.' },
  { name: '--warn-600', target: '--color-warn-600', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-25', target: '--color-danger-25', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-50', target: '--color-danger-50', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-100', target: '--color-danger-100', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-200', target: '--color-danger-200', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-400', target: '--color-danger-400', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-500', target: '--color-danger-500', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-600', target: '--color-danger-600', description: 'Kura short-ramp compatibility alias.' },
  { name: '--danger-700', target: '--color-danger-700', description: 'Kura short-ramp compatibility alias.' },
  { name: '--info-100', target: '--color-info-100', description: 'Kura short-ramp compatibility alias.' },
  { name: '--info-500', target: '--color-info-500', description: 'Kura short-ramp compatibility alias.' },
  { name: '--info-600', target: '--color-info-600', description: 'Kura short-ramp compatibility alias.' },
  {
    name: '--color-text-muted',
    target: '--color-text-tertiary',
    description: 'Kura muted text compatibility alias resolving to #6b7388 in light mode.',
  },
  { name: '--color-text-placeholder', target: '--color-ink-400', description: 'Kura placeholder text bridge.' },
  { name: '--color-text-link-hover', target: '--color-brand-700', description: 'Kura hover-link bridge.' },
  {
    name: '--surface-bg',
    target: '--color-surface-bg',
    description: 'Kura page-background source input in light and canonical alias in dark.',
  },
  { name: '--bg', target: '--color-surface-bg', description: 'Kura page-background compatibility alias.' },
  { name: '--surface-raised', target: '--color-surface', description: 'Kura raised-surface compatibility alias.' },
  { name: '--border-color', target: '--color-border', description: 'Kura shadcn border bridge.' },
  { name: '--border-emphasis', target: '--color-border-emphasis', description: 'Kura border compatibility alias.' },
  { name: '--border-focus', target: '--color-border-focus', description: 'Kura focus-border compatibility alias.' },
  { name: '--badge-neutral-border', target: '--color-badge-neutral-border', description: 'Kura badge compatibility alias.' },
  { name: '--badge-neutral-icon', target: '--color-badge-neutral-icon', description: 'Kura badge compatibility alias.' },
  { name: '--badge-warning-icon', target: '--color-badge-warning-icon', description: 'Kura badge compatibility alias.' },
  { name: '--status-low-fg', target: '--color-status-low-fg', description: 'Kura lone low-status foreground alias.' },
  { name: '--status-ai-bg', target: '--color-status-ai-bg', description: 'Kura AI-status background alias.' },
  { name: '--status-ai-fg', target: '--color-status-ai-fg', description: 'Kura AI-status foreground alias.' },
] as const satisfies readonly ColorAlias[];

export const KURA_COLOR_EXTENSIONS = [
  { name: '--brand-200', group: 'Brand', value: '#a3d0ff', description: 'Kura palette extension.', swatch: true },
  { name: '--brand-300', group: 'Brand', value: '#7dbaff', description: 'Kura palette extension.', swatch: true },
  { name: '--brand-400', group: 'Brand', value: '#52a2ff', description: 'Kura palette extension.', swatch: true },
  { name: '--brand-900', group: 'Brand', value: '#04234d', description: 'Kura palette extension.', swatch: true },
  {
    name: '--brand-rgb',
    group: 'Brand',
    value: '38, 140, 255',
    description: 'Kura RGB channel metadata; not a swatch.',
    swatch: false,
  },
  { name: '--secondary-deep-600', group: 'Secondary Deep', value: '#0c0483', description: 'Kura palette extension.', swatch: true },
  { name: '--secondary-deep-700', group: 'Secondary Deep', value: '#090364', description: 'Kura palette extension.', swatch: true },
  { name: '--secondary-light-300', group: 'Secondary Light', value: '#60cdff', description: 'Kura palette extension.', swatch: true },
  { name: '--secondary-light-500', group: 'Secondary Light', value: '#0ab0e5', description: 'Kura palette extension.', swatch: true },
  { name: '--secondary-light-700', group: 'Secondary Light', value: '#0787af', description: 'Kura palette extension.', swatch: true },
  { name: '--ink-300', group: 'Ink', value: '#c2c7d4', description: 'Kura palette extension.', swatch: true },
  { name: '--ink-800', group: 'Ink', value: '#1a2335', description: 'Kura palette extension.', swatch: true },
  { name: '--success-700', group: 'Success', value: '#13744a', description: 'Kura palette extension.', swatch: true },
  { name: '--warn-700', group: 'Warn', value: '#a55b04', description: 'Kura palette extension.', swatch: true },
  { name: '--info-50', group: 'Info', value: '#e6f9fd', description: 'Kura palette extension.', swatch: true },
  { name: '--info-700', group: 'Info', value: '#0a5870', description: 'Kura palette extension.', swatch: true },
  { name: '--purple-50', group: 'Purple', value: '#f0eafb', description: 'Kura palette extension.', swatch: true },
  { name: '--purple-500', group: 'Purple', value: '#6a35c0', description: 'Kura palette extension.', swatch: true },
  { name: '--purple-700', group: 'Purple', value: '#4e2490', description: 'Kura palette extension.', swatch: true },
] as const satisfies readonly KuraColorExtension[];

export const DCM_SEMANTIC_TONE_RULES = [
  {
    tone: 'neutral',
    meanings: ['normal', 'inactive', 'unknown', 'no-reference'],
    foreground: '--color-status-neutral-fg',
    background: '--color-status-neutral-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use neutral ink for ordinary, missing, inactive, or metadata states.',
  },
  {
    tone: 'info',
    meanings: ['informational'],
    foreground: '--color-status-info-fg',
    background: '--color-status-info-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use info for context that informs without requiring correction.',
  },
  {
    tone: 'success',
    meanings: ['completed', 'verified', 'in-range', 'stable'],
    foreground: '--color-status-success-fg',
    background: '--color-status-success-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use success only for confirmed, completed, verified, or stable outcomes.',
  },
  {
    tone: 'warning',
    meanings: ['pending', 'review', 'out-of-reference', 'recoverable'],
    foreground: '--color-status-warning-fg',
    background: '--color-status-warning-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use warning for review, pending work, reference exceptions, or recoverable issues.',
  },
  {
    tone: 'danger',
    meanings: ['critical', 'destructive', 'blocked', 'privacy', 'safety', 'payment failure'],
    foreground: '--color-status-danger-fg',
    background: '--color-status-danger-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use danger for critical or destructive states and privacy, safety, or payment failures.',
  },
  {
    tone: 'ai',
    meanings: ['AI-assisted', 'generated insight'],
    foreground: '--color-status-ai-fg',
    background: '--color-status-ai-bg',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Reserve purple AI tone for AI-assisted suggestions and generated insight.',
  },
  {
    tone: 'brand',
    meanings: ['primary action', 'selected navigation', 'active focus'],
    foreground: '--color-brand-500',
    background: '--color-brand-50',
    requirement: 'Text or icon cue required; never color-only',
    description: 'Use brand blue for primary action, selected navigation, links, and active focus.',
  },
] as const satisfies readonly DcmSemanticToneRule[];
